
package io.chillout.redditgrab.Model;

import java.util.List;

public class CrosspostParentList {

    public Object approvedAtUtc;
    public String subreddit;
    public String selftext;
    public String authorFullname;
    public Boolean saved;
    public Object modReasonTitle;
    public Integer gilded;
    public Boolean clicked;
    public String title;
    public List<Object> linkFlairRichtext = null;
    public String subredditNamePrefixed;
    public Boolean hidden;
    public Object pwls;
    public Object linkFlairCssClass;
    public Integer downs;
    public Integer thumbnailHeight;
    public Boolean hideScore;
    public String name;
    public Boolean quarantine;
    public String linkFlairTextColor;
    public Object authorFlairBackgroundColor;
    public String subredditType;
    public Integer ups;
    public Integer totalAwardsReceived;
    public MediaEmbed_ mediaEmbed;
    public Integer thumbnailWidth;
    public Object authorFlairTemplateId;
    public Boolean isOriginalContent;
    public List<Object> userReports = null;
    public Object secureMedia;
    public Boolean isRedditMediaDomain;
    public Boolean isMeta;
    public Object category;
    public SecureMediaEmbed_ secureMediaEmbed;
    public Object linkFlairText;
    public Boolean canModPost;
    public Integer score;
    public Object approvedBy;
    public String thumbnail;
    public Boolean edited;
    public Object authorFlairCssClass;
    public List<Object> stewardReports = null;
    public List<Object> authorFlairRichtext = null;
    public Gildings_ gildings;
    public String postHint;
    public Object contentCategories;
    public Boolean isSelf;
    public Object modNote;
    public Float created;
    public String linkFlairType;
    public Object wls;
    public Object bannedBy;
    public String authorFlairType;
    public String domain;
    public Boolean allowLiveComments;
    public Object selftextHtml;
    public Object likes;
    public String suggestedSort;
    public Object bannedAtUtc;
    public Object viewCount;
    public Boolean archived;
    public Boolean noFollow;
    public Boolean isCrosspostable;
    public Boolean pinned;
    public Boolean over18;
    public Preview_ preview;
    public List<Object> allAwardings = null;
    public Boolean mediaOnly;
    public Boolean canGild;
    public Boolean spoiler;
    public Boolean locked;
    public Object authorFlairText;
    public Boolean visited;
    public Object numReports;
    public Object distinguished;
    public String subredditId;
    public Object modReasonBy;
    public Object removalReason;
    public String linkFlairBackgroundColor;
    public String id;
    public Boolean isRobotIndexable;
    public Object reportReasons;
    public String author;
    public Integer numCrossposts;
    public Integer numComments;
    public Boolean sendReplies;
    public Object whitelistStatus;
    public Boolean contestMode;
    public List<Object> modReports = null;
    public Boolean authorPatreonFlair;
    public Object authorFlairTextColor;
    public String permalink;
    public Object parentWhitelistStatus;
    public Boolean stickied;
    public String url;
    public Integer subredditSubscribers;
    public Float createdUtc;
    public Object discussionType;
    public Object media;
    public Boolean isVideo;

}
